### PR TITLE
Fix: NullPointerException in the user list GUI.

### PR DESCRIPTION
**Pull request by apachezy**
In the user list GUI, click to switch the display mode, you may encounter a null pointer exception.

### CODE REVIEW

**Review by BONNe — COMMENTED** [review]
Player UUID cannot be null.
If it is null, something is wrong.

UUID is the official way how players are identified.

**Comment by apachezy** [comment]
Yes, usually the user UUID must not be NULL.
But I did have this kind of problem here, and the cause of the problem may be inside BentoBox.
```
[14:51:40] [Server thread/ERROR]: Could not pass event InventoryClickEvent to BentoBox v1.16.0
java.lang.NullPointerException: null
	at world.bentobox.challenges.panel.admin.ListUsersGUI.createPlayerIcon(ListUsersGUI.java:195) ~[?:?]
	at world.bentobox.challenges.panel.admin.ListUsersGUI.build(ListUsersGUI.java:155) ~[?:?]
	at world.bentobox.challenges.panel.admin.ListUsersGUI.lambda$createToggleButton$8(ListUsersGUI.java:338) ~[?:?]
	at world.bentobox.bentobox.listeners.PanelListenerManager.lambda$onInventoryClick$0(PanelListenerManager.java:56) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at world.bentobox.bentobox.listeners.PanelListenerManager.onInventoryClick(PanelListenerManager.java:54) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor386.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-1.16.4.jar:git-Paper-416]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-1.16.4.jar:git-Paper-416]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-1.16.4.jar:git-Paper-416]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[paper-1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2540) ~[paper-1.16.4.jar:git-Paper-416]
```

**Comment by BONNe** [comment]
In that case, I would like to see `Players` database, if that is possible.
As it would mean, that there is a player with incorrect data in it.

**Comment by apachezy** [comment]
Okay, here is the database:
[database.zip](https://github.com/BentoBoxWorld/Challenges/files/6103751/database.zip)

**Pull request closed without merging**
