### PR TITLE
Adapt literal style

### PR DESCRIPTION
**Pull request by N0tMyFaultOG**
Follow up to #192

### CODE REVIEW

**Comment by BONNe** [comment]
And how it looks in chat and in GUIs?
Is it ok?  (your thoughts)

**Comment by N0tMyFaultOG** [comment]
It looks perfectly fine, also more clean.

Top: With my pr
Bottom: Currently

**Comment by BONNe** [comment]
And GUIS,... as these error messages are not so important.

**Comment by N0tMyFaultOG** [comment]
GUIs are not affected by the change, they still look how they are

**Comment by BONNe** [comment]
Overall I like it, but I will wait until gitLocalize fix their side before merging.

**Comment by N0tMyFaultOG** [comment]
I had no luck with git localize in the past, I couldn't log in at all smh, that's why I used to open prs ^^

**Pull request merged**
