### PR TITLE
Make default translation looking a bit nicer

### PR DESCRIPTION
**Pull request by N0tMyFaultOG**
Minor modifications to make challenges looking a bit nicer and friendlier. Also generalizing capitalization.

### CODE REVIEW

**Comment by BONNe** [comment]
I get it that nobody likes large letters in names.
But why use a new line with a space in front? [(link)](https://github.com/BentoBoxWorld/Challenges/pull/192/files#diff-bf7713c923dcd49b899d47c2f518036bR17)
```
'Import challenges from challenges.yml | Parameter overwrite means that challenges or levels with the same ID will be overwritten.'
```
will look like:
```
Import challenges from challenges.yml 
 Parameter overwrite means that challenges or levels with the same ID will be overwritten.
```

By the way. Thanks for improvements.

**Comment by N0tMyFaultOG** [comment]
Oh, so you use the pipe as line break? I wasn't sure about its purpose so I assumed it's a spacer, because rn, it looks like that 
https://github.com/BentoBoxWorld/Challenges/blob/967e6e05a248c111014e29a7bb29f860bdefa6b7/src/main/resources/locales/en-US.yml#L459
I edited my file and changed it using the literal style, so it actually breaks lines:
```yaml
not-valid-integer: |
      &cGiven integer "[value]" is not valid!
      Value should be between [min] and [max].
```

If the changes with the spaced pipes are unwanted, I can surely revert them, but I guess other fields are looking the same way, because adding a pipe between a statement doesn't enforce a line break iirc.

**Comment by Poslovitch** [comment]
I'd actually also prefer line breaks to be made using the YAML built-in format, instead of using `|` as "custom" line breaks.

**Comment by N0tMyFaultOG** [comment]
I rewrote the en-US translation using the block scalar literal style. Line breaks are now working as expected and the file uses the built in formats.

**Comment by N0tMyFaultOG** [comment]
Oh, that has already been merged, neato. Yet I just noticed I didn't check out the changes I made to the translation files in the new yaml style. If you're still interested I could provide them @Poslovitch @BONNe

**Comment by BONNe** [comment]
You can do it in a new PR :)

**Pull request merged**
