### PR TITLE
Prepare 1.0 Release

### PR DESCRIPTION
**Pull request by BONNe**
This is preparation for 1.0 release.
Update to Pladdon and BentoBox 1.17.3 changes.

This includes a lot of changes:
- Customizable GUI's
- Statistic Challenge Type
- All translations rework
- Fixes bug with the missing global command
- Move Challenges and Levels lore to the locales.
- Readd template.yml file
- Implement easier database exporting and importing
- Implement a better Item, Material, Entity translation scheme.
- Adds timeout option for challenges
- Adds "ignore" metadata per inventory challenge
- Some other bugfixes

### CODE REVIEW

**Comment by Poslovitch** [comment]
Wow, there are a lot of things to review!
Are the failing builds expected?

**Comment by BONNe** [comment]
> Wow, there are a lot of things to review! Are the failing builds expected?

Yes and no :D

I forgot to remove "NMS" dependency.  Should be fixed now.

About review... well... yea... sorry.

**Comment by OverBrave** [comment]
Hello, is it still time for version 1.0 to come out? Is it okay for the transition now? And is it compatible with the old "challenges" database? So I can continue to use my old challenges?

**Comment by BONNe** [comment]
Yes. Merge is not happened, because it requires at least 1 review from devs.

**Review by tastybento — APPROVED** [review]
There's too much to review of course, but I've scanned with tools and fixed the bugs from the static code analysis and fixed the tests.

**Pull request merged**
